### ISSUE TITLE
Missing section for spike in DATA_README.md

### ISSUE THREAD

**Issue by methi1999** [cxrodgers/Rodgers2021#1]
In DATA_README.md, the explanation for the session-specific file _spike_ is missing while the section for _neural_trial_timings_ appears twice.

**Comment by cxrodgers** [comment]
@methi1999 Thanks for reporting this. I have fixed the documentation. 

Please also see a new version of this dataset at https://dandiarchive.org/dandiset/000231 and related preprint at https://www.biorxiv.org/content/10.1101/2022.05.10.491259v1. The advantage of the new dataset is that it includes more raw data (the entire electrophysiological recording, all the videos), and it is in the NWB format. However, this `Rodgers2021` dataset remains useful for replicating the analyses presented in my original paper.
